sample/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

users/urls.py
from django.urls import path

from . import views

app_name='users'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:cadet_id>/', views.detail, name='detail'),
    path('<int:cadet_id>/update', views.update, name='update'),
    path('add', views.addcadet, name='addcadet'),
    path('addcompany', views.addcompany, name='addcompany'),
]

users/models.py
from django.db import models

class Company(models.Model):
    shortname = models.CharField(max_length=1) #A, B, C, etc.
    longname = models.CharField(max_length=50) #Alpha, Bravo, Charlie etc.
    regiment = models.IntegerField() #1,2,3,4
    motto = models.CharField(max_length=100) #Go Buffs!  Go Greeks, etc.
    mascot = models.CharField(max_length=100) #Buffalos, Greeks.

    def __str__(self):
        return (self.shortname + "-" + str(self.regiment))

class Cadet(models.Model):
    first = models.CharField(max_length=200)
    last = models.CharField(max_length=200)
    xnumber = models.CharField(max_length=8)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, default=1)

    def name(self):
        return (self.last + ", " + self.first)
    def __str__(self):
        return (self.last + ", " + self.first)

users/forms.py
from .models import Cadet, Company
from django import forms

class CadetForm(forms.ModelForm):
    class Meta:
        model = Cadet
        fields = '__all__'

class CompanyForm(forms.ModelForm):
    class Meta:
        model = Company
        fields = '__all__'

users/views.py
from django.shortcuts import render
from django.template import loader
from .models import Cadet
from .models import Company
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from .forms import CadetForm
from .forms import CompanyForm

# Create your views here.
def index(request):
    cadets = Cadet.objects.all() #Grab all cadets from database
    context = {'cadets': cadets} #fill a context with the cadet list
    template = loader.get_template('users/index.html') #Get the template we created
    return HttpResponse(template.render(context, request)) #Render the template with the context

def detail(request, cadet_id):
    try:
        cadet = Cadet.objects.get(pk=cadet_id)
        companies = Company.objects.all()
        context = {'cadet':cadet, 'companies': companies}
    except Cadet.DoesNotExist:
        raise Http404("Cadet does not exist")
    return render(request, 'users/detail.html', context)

def update(request, cadet_id):
    new_xnumber = request.POST['xnumber']
    new_company_id = request.POST['company_id']
    cadet = Cadet.objects.get(pk=cadet_id)
    cadet.xnumber = new_xnumber
    cadet.company_id = new_company_id
    cadet.save()
    companies = Company.objects.all()
    context = {'cadet':cadet, 'companies': companies}
    return render(request, 'users/detail.html', context)

def addcadet(request):
    if request.user.is_authenticated:
        if request.user.has_perm('user.add_cadet'):
            print("add perm found")
        else:
            print("no perm found")
            dir(request.user)
        if request.method == 'POST':
            form = CadetForm(request.POST)
            if form.is_valid():
                #Add the cadet to the database
                newcadet = form.save()
                #Go back to cadet list
                return HttpResponseRedirect('/users')
        else:
            form = CadetForm()
        return render(request, 'users/add.html', {'form': form})
        #else:
            #return HttpResponseRedirect('/users')

    else:
        print("user not authenticated")
        return (HttpResponse("You are not allowed to add cadets"))

def addcompany(request):
    #if user.has_perm('cadet.add_cadet'):
    if request.method == 'POST':
        form = CompanyForm(request.POST)
        if form.is_valid():
            #Add the company to the database
            newcompany = form.save()
            #Go back to cadet list
            return HttpResponseRedirect('/users')
    else:
        form = CompanyForm()
    return render(request, 'users/addcompany.html', {'form': form})

users/templates/users/add.html
{% extends 'users/base_generic.html' %}
{% block content %}
{% if user.is_authenticated and perms.user.add_cadet %}
<form action="add" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>
{% else %}
Sorry, you do not have access to add cadets

{% endif %}

{% endblock %}

users/templates/users/addcompany.html
{% extends 'users/base_generic.html' %}
{% block content %}
{% if user.is_authenticated %}

<form action="addcompany" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit" />
</form>

{% else %}
<a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}

users/templates/users/base_generic.html
{% load static %}
<!DOCTYPE HTML>
<!--
	Theory by TEMPLATED
	templated.co @templatedco
	Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>
	<head>
		<title>Cadet Management</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<link rel="stylesheet" href="{% static "assets/css/main.css" %}" />
	</head>
	<body>

		<!-- Header -->
			<header id="header">
				<div class="inner">
					<a href="index.html" class="logo">Main</a>
					<nav id="nav">
						<a href="index.html">Home</a>
						<a href="generic.html">Generic</a>
						<a href="elements.html">Elements</a>
					</nav>
					<a href="#navPanel" class="navPanelToggle"><span class="fa fa-bars"></span></a>
				</div>
			</header>

		<!-- Banner -->
			<section id="banner">
				<h1>Welcome to Cadet Management System</h1>
				<p>A sample django site with a css template.</p>
			</section>

		<!-- One -->
			<section id="one" class="wrapper">
				<div class="inner">
					<div class="flex flex-3">
						
						{% block content %}
				        {% endblock %}
					</div>
				</div>
			</section>

		

		<!-- Footer -->
			<footer id="footer">
				<div class="inner">
					<div class="flex">
						<div class="copyright">
							&copy; Untitled. Design: <a href="https://templated.co">TEMPLATED</a>. Images: <a href="https://unsplash.com">Unsplash</a>.
						</div>
						<ul class="icons">
							<li><a href="#" class="icon fa-facebook"><span class="label">Facebook</span></a></li>
							<li><a href="#" class="icon fa-twitter"><span class="label">Twitter</span></a></li>
							<li><a href="#" class="icon fa-linkedin"><span class="label">linkedIn</span></a></li>
							<li><a href="#" class="icon fa-pinterest-p"><span class="label">Pinterest</span></a></li>
							<li><a href="#" class="icon fa-vimeo"><span class="label">Vimeo</span></a></li>
						</ul>
					</div>
				</div>
			</footer>

		<!-- Scripts -->
			<script src="{% static "assets/js/jquery.min.js" %}"></script>
			<script src="{% static "assets/js/skel.min.js" %}"></script>
			<script src="{% static "assets/js/util.js" %}"></script>
			<script src="{% static "assets/js/main.js" %}"></script>

	</body>
</html>

users/templates/users/detail.html
<h1>{{ cadet.name }}</h1>

<ul>
   <li>Xnumber: {{ cadet.xnumber }}</li>
   <li>Company: {{ cadet.company.shortname}}-{{ cadet.company.regiment}}</li>

<br />
Now we add a form to edit the cadet's properties.
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'users:update' cadet.id %}" method="post">
{% csrf_token %} 
<input type="text" name="xnumber" value="{{cadet.xnumber}}" />
<select name="company_id">
    {% for company in companies %}
    
    <option value="{{company.id}}" 
    {% if cadet.company.id == company.id %} 
     selected
    {% endif %}

    >{{company}}</option>
    {% endfor %}
</select>
<input type="submit" value="Update cadet" />
</form>
</ul>

users/templates/users/index.html
{% extends 'users/base_generic.html' %}
{% block content %}
{% if user.is_authenticated %}
<p>Welcome, {{ user.get_username }}.  
<a href="{% url 'logout' %}">Log Out</a>
{% else %}
<a href="{% url 'login' %}">Log In</a>
{% endif %}
<p>
<h2>Cadet List</h2>

{% if cadets %} <!-- check if list is full or empty -->
<ul>

  {% for cadet in cadets %}
      <li><a href="./{{cadet.id}}">{{cadet.name}}</a> {{cadet.company}}</li>
  {% endfor %}

</ul>
{% else %}
<p>No cadets in database</p>
{% endif %}

{% if user.is_authenticated and perms.user.add_cadet %}
<a href="add">Add cadet to database</a>
{% endif %}
</p>

{% endblock %}